---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cmb-webstore
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # repoURL: https://github.com/ressafri/cmb-k8s.git
    repoURL: https://github.com/ressafri/test-delete-me.git
    targetRevision: HEAD
    path: cmb/cmb-webstore
  destination:
    server: https://kubernetes.default.svc
    # namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PruePropagationPolicy=foreground
      - PruneLast=true