---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cmb-webstore
  namespace: argocd
spec:
  project: default
  source:
    # repoURL: https://github.com/ressafri/cmb-k8s.git
    repoURL: https://github.com/anonputra/lesson-158.git
    targetRevision: HEAD
    path: cmb-webstore
  destination:
    server: https://kubernetes.default.svc
    # namespace: default
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true