---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cmb-webstore
  namespace: cmb-production
  labels:
    app: cmb-webstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cmb-webstore
  spec:
    containers:
      - name: cmb-webstore
        image: ressafri/nginx:1.29.3-alpine
        ports:
          - containerPort: 80